### ISSUE TITLE
ending doublequotes missing

### ISSUE THREAD

**Issue by ronmurphy** [coding-horror/donkey.bas#1]
in lines 92,93,94 and 103.

**Comment by oznogon** [comment]
They're not present in the source.

![screen shot 2016-07-18 at 11 25 25 am](https://cloud.githubusercontent.com/assets/1296917/16925739/743088c8-4cda-11e6-8038-e6fa9bca2832.png)

Via http://www.pcjs.org/devices/pcx86/machine/5150/cga/64kb/donkey/

**Comment by ronmurphy** [comment]
odd, ok.

**Comment by OvermindDL1** [comment]
In old BASIC trailing double quotes were optional if the last thing on the line (a newline acts like a closing double quote if there was an open string).

**Comment by ronmurphy** [comment]
ah ok.  i always closed mine because i read it in a book that it should be done, good practice i guess.
