### ISSUE TITLE
Add a README.md

### ISSUE THREAD

**Issue by ghost** [coding-horror/donkey.bas#5]
Hello coding-horror, I am MrGithub2021 and I want you to make a README.md so that people can understand it better. I can' t understand what the purpose of your project is clearly ad others might just see this a junk. So, coding-horror, I want you to make a README.md. Sincerely, MrGithub2021.

**Comment by coding-horror** [comment]
OK! Feel free to send through a pull request if you'd like to assist!

**Comment by MrGithub2021** [comment]
Thanks! Do you want to look at one of my projects?

**Comment by ghost** [comment]
Also, the description is a bit weird.

**Comment by MrGithub2021** [comment]
So, what do you want the README to be like? Funny? Serious? Informative?

**Comment by MrGithub2021** [comment]
BTW, do you like questions?

**Comment by ghost** [comment]
Also, what was the purpose of this project?

**Comment by ghost** [comment]
That's all I need for the README. Thanks.

**Comment by ghost** [comment]
Okay, I sent you the pull request.

**Comment by ghost** [comment]
Here is the forked project of mine:https://github.com/MrGithub2021/donkey.bas.
