### ISSUE TITLE
Update GitHub language breakdown

### ISSUE THREAD

**Issue by DecimalTurn** [coding-horror/donkey.bas#8]
Currently, the language breakdown of the repo indicates `VBA` instead of `BASIC`. That's because the last change made to the repo was done before `BASIC` was added to the Linguist project on GitHub ([v7.14](https://github.com/github-linguist/linguist/releases/tag/v7.14.0#:~:text=Add%20support%20for%20the%20BASIC%20family%20of%20programming%20languages%20(%235166))).

Normally, any changes (even a space added to the README) would be enough to trigger a new analysis by Linguist of the languages in the repo. Therefore, it would be nice to push a fictitious change so this project can appear correctly labeled as a BASIC project when people search on GitHub.

**Comment by coding-horror** [comment]
cool!  Did we push any changes through that made it work?

**Comment by DecimalTurn** [comment]
No _concrete_ changes to this repo are/were needed to make it work, it was Linguist that didn't know about `BASIC` until v7.14 and the "wrong" analysis of this repo remains cached on GitHub until a new commit is pushed to this repo.

**Comment by coding-horror** [comment]
ok, what do you recommend we do?

**Comment by DecimalTurn** [comment]
Adding another exclamation point to the README perhaps?

**Comment by coding-horror** [comment]
done!

**Comment by DecimalTurn** [comment]
Beautiful!

**Comment by coding-horror** [comment]
shoot me an email jatwood at codinghorror dot com, I'd like to mail you a little something as thanks if that's OK with you? 🎁
